name: CI

on:
  push:
    branches:
    - master
  

jobs:
  job0:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2018.4.9f1
    steps:

      - run: mkdir -p path/to/artifact

      - name: Opt
        run: |
          cp /opt/Unity/Editor/Data/Managed/UnityEngine/UnityEngine.CoreModule.dll path/to/artifact

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact