name: CI

on:
  push:
    branches:
    - master
  

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:

      - uses: pCYSl5EDgo/UnityCreateLicenseFile@master
        with:
          unity-tag: 2018.4.9f1
          directory: XXX