name: CI

on:
  push:
    branches:
    - master
  

jobs:
  job0:
    uses: docker://gableroux/unity3d:2018.4.9f1
    with:
      args: echo "HogeHoge"
  job1:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100-rc1-014190'
    - run: dotnet run
