name: CI

on:
  push:
    branches:
    - master
  

jobs:
  job0:
    container: gableroux/unity3d:2018.4.9f1
    steps:
      
      - name: Show Current Directory
        run: |
          pwd
          ls
        
